### ISSUE TITLE
Searching by Catalog ID doesn't work

### ISSUE THREAD

**Issue by aberamseyer** [gamehelp16/monstercat-browser#1]
Or I don't understand how it should work. Just as a test I typed "MCS235", "235", and "MCS#235" in the search bar and none of them gave a result. This was tested in all categories. If that feature wasn't intended to be supported, remove the text from the search bar box. 

Expected behavior: link to the page https://gamehelp16.github.io/monstercat-browser/#/MCS235

**Comment by gamehelp16** [comment]
The filter only filters from the shown results. I think you haven't scrolled down far enough yet for MCS235 to appear (since it's a pretty old one) and that's why it didn't appear on the filter results.

I know that it's pretty inconvenient that the filter only filters from results that are shown, but imagine this scenario: there are only 30 singles shown but when you filter using "M" then all 500+ singles will be shown since they all have "M" on their catalog id which kills the purpose of not showing all singles on the first place (this applies not just for singles btw). And if you wonder why I chose to show only a few singles on the first load is because downloading all 500+ album art is bandwidth heavy and some users won't probably look at them all anyway.

If you know the exact catalog id for the album you are looking for simply just change the URL and it will instantly load :)

**Comment by chez14** [comment]
so that kind of feature are requiring server-side management, right?

**Comment by gamehelp16** [comment]
Which feature?
